name = "ReversedSeries"
uuid = "87ffe17a-2ae0-4c33-b274-0f3657b00e05"
authors = ["gg <gg@nowhere> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
